name: inject.example.coffee
description: A simple example of using package:inject

dependencies:
  inject:
    path: ../../package/inject

dev_dependencies:
  build_runner: ^1.10.4
  build_test: ^0.10.1+1
  build_web_compilers: ^2.13.0
  inject_generator:
    path: ../../package/inject_generator
  test: ^1.0.0
